### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by marxin** [microsoft/dia-rs#32]
Can you please make a new release that will use the latest `windows-core` crate (0.59)?

**Comment by riverar** [comment]
Hey @marxin, will do.

Have you had an opportunity to switch your crate(s) to master to verify that nothing is seriously broken?

```toml
[dependencies.dia-rs]
git = "https://github.com/microsoft/dia-rs"
branch = "master"
```
